---
# vars file for docker
docker_system_arch: 'amd64'
docker_base_url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}'
docker_repository: 'deb [arch={{ docker_system_arch }}] {{ docker_base_url }} {{ ansible_distribution_release }} stable'

docker_deprecated_packages:
  - docker
  - docker-engine
  - docker.io
  - container.d
  - runc

docker_required_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
